CREATE TABLE `actor` (
  `ID` int(11) NOT NULL,
  `OSCARNOMINATIONS` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_ACTOR_ID` FOREIGN KEY (`ID`) REFERENCES `person` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;